# Generated by Django 4.2.6 on 2023-10-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0002_alter_events_maquina_alter_events_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.maquina'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='events',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.tecnico'),
        ),
    ]
