# Generated by Django 4.2.6 on 2023-10-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0004_location_remove_permission_menu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ejecucion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='tecnico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.tecnico'),
        ),
    ]
