# Generated by Django 4.2.6 on 2023-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0006_status_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
