# Generated by Django 4.2.6 on 2023-10-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0006_alter_day_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
    ]
