# Generated by Django 4.2.6 on 2023-10-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0007_alter_role_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='active',
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.events'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.location'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
    ]
