# Generated by Django 4.2.6 on 2023-10-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0007_alter_status_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.menu'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.role'),
        ),
    ]
