# Generated by Django 4.2.6 on 2023-10-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0008_remove_menu_active_menu_status_alter_events_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_orden',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
