# Generated by Django 4.2.6 on 2023-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0008_remove_permission_menu_remove_permission_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
