# Generated by Django 4.2.6 on 2023-10-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0010_alter_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.maquina'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
    ]
