# Generated by Django 4.2.6 on 2023-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0011_alter_user_managers_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
