# Generated by Django 4.2.6 on 2023-10-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0012_alter_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
