# Generated by Django 4.2.6 on 2023-10-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status'),
        ),
    ]
