# Generated by Django 4.2.6 on 2023-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0013_user_location_alter_user_role_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_login',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
