# Generated by Django 4.2.6 on 2023-10-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0014_remove_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='ultimo_mantenimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
