# Generated by Django 4.2.6 on 2023-10-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0014_user_is_owner_user_user_lastname_user_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.CharField(max_length=200, null=True, unique=True)),
                ('trabajo_realizado', models.CharField(max_length=200, null=True)),
                ('diagnostico', models.CharField(max_length=200, null=True)),
                ('actividades', models.CharField(max_length=200, null=True)),
                ('causas', models.CharField(max_length=200, null=True)),
                ('observacion', models.CharField(max_length=200, null=True)),
                ('hora_inicio', models.CharField(max_length=200, null=True)),
                ('hora_fin', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.events')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.status')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.tecnico')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.user')),
            ],
        ),
    ]
