# Generated by Django 4.2.6 on 2023-10-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0015_alter_maquina_ultimo_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
