# Generated by Django 4.2.6 on 2023-11-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0016_menu_menu_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantix_pro.day'),
        ),
    ]
