# Generated by Django 4.2.6 on 2023-11-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0018_alter_day_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateField(),
        ),
    ]
