# Generated by Django 4.2.6 on 2023-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0019_alter_events_end_alter_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='dayDate',
            field=models.DateField(null=True),
        ),
    ]
