# Generated by Django 4.2.6 on 2023-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0020_alter_day_daydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_orden',
            field=models.IntegerField(null=True),
        ),
    ]
