# Generated by Django 4.2.6 on 2023-11-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0022_alter_events_end_alter_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
