# Generated by Django 4.2.6 on 2023-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantix_pro', '0023_alter_workorder_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='maquina_name',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
